# Generated by Django 5.0.4 on 2024-04-20 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=255)),
                ('sheet_id', models.CharField(max_length=255)),
                ('xml_id', models.CharField(max_length=255)),
                ('time_web_token', models.CharField(max_length=255)),
                ('avito_client_id', models.CharField(max_length=255)),
                ('avito_client_secret', models.CharField(max_length=255)),
                ('image', models.CharField(default=None, max_length=255, null=True)),
                ('bucket', models.CharField(default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
