# Generated by Django 5.0.4 on 2024-04-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify_token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
