# Generated by Django 5.0.4 on 2024-04-21 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_email_verified_at_user_email_verify_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('adverts_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='remaining_options',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'customer')], default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tariffoption'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tariffoption'),
        ),
    ]
