# Generated by Django 5.0.4 on 2024-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_tariff_options_remove_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
